### ISSUE TITLE
TDP template for 2018

### ISSUE THREAD

**Issue by tkelestemur** [RoboCupAtHome/TDPTemplate#2]
I saw that there is branch called `template2018` which is not merged to master. Should we use the `master` or `template2018` for this year's qualification? There is not much difference but just wanted to be sure.

**Comment by kyordhel** [comment]
Thanks @LoyVanBeek 
@tkelestemur thanks for the reminder, I totally forgot to update the template.

I just update the template in commit 2ae3be5, so no branch problem.
